name: Gerar APK Paulo Luna

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Gerar estrutura nativa Android sem conflitos
        run: |
          flutter config --no-analytics
          cp pubspec.yaml pubspec.yaml.bak
          rm -rf android
          flutter create . --platforms=android --org com.example --project-name app_paulo_luna
          cp pubspec.yaml.bak pubspec.yaml

      - name: Configurar Permissoes de Sobreposicao
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>\n    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>' android/app/src/main/AndroidManifest.xml

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: PauloLuna-App
          path: build/app/outputs/flutter-apk/app-release.apk
